---
apiVersion: networking.gke.io/v1beta1
kind: FrontendConfig
metadata:
  name: apple-frontend-config
  namespace: kube
spec:
  # Remove sslPolicy for testing without SSL
  # sslPolicy: us-ssl-security

  # Optional HTTP â†’ HTTPS redirect (disable for plain HTTP testing)
  redirectToHttps:
    enabled: false

