---
apiVersion: networking.gke.io/v1beta1
kind: FrontendConfig
metadata:
  name: apple-frontend-config
  namespace: kube
spec:
  sslPolicy: us-ssl-security
  redirectToHttps:
    enabled: true
    responseCodeName: "301"
---
