apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: apple-ingress
  namespace: kube
  annotations:
    cloud.google.com/load-balancer-neg-ready: "true"
    cloud.google.com/neg: '{"ingress": true}'
    networking.gke.io/v1beta1.FrontendConfig: apple-frontend-config
    kubernetes.io/ingress.global-static-ip-name: apple-ingress-staticip
spec:
  tls:
  - hosts:
    - pc-app.profitokr.net
    secretName: profitokrs-tls-2025
  - hosts:
    - pc-files.profitokr.net
    secretName: profitokrs-tls-2025
  rules:
  - host: pc-app.profitokr.net
    http:
      paths:
      - backend:
          service:
            name: kube-app-svc
            port:
              number: 80
        path: /*
        pathType: ImplementationSpecific
  - host: pc-files.profitokr.net
    http:
      paths:
      - backend:
          service:
            name: kube-files-svc
            port:
              number: 80
        path: /*
        pathType: ImplementationSpecific
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: internal-ingress
  namespace: kube
  annotations:
    cloud.google.com/load-balancer-neg-ready: "true"
    kubernetes.io/ingress.allow-http: "false"
    kubernetes.io/ingress.class: gce-internal
    kubernetes.io/ingress.regional-static-ip-name: internal-ingress-static-ip
spec:
  tls:
  - hosts:
    - pc-api.profitokr.net
    secretName: profitokrs-tls-2025
  - hosts:
    - pc-pubsub.profitokr.net
    secretName: profitokrs-tls-2025
  - hosts:
    - pc-enq.profitokr.net
    secretName: profitokrs-tls-2025
  - hosts:
    - pc-ams.profitokr.net
    secretName: profitokrs-tls-2025
  - hosts:
    - pc-esvc.profitokr.net
    secretName: profitokrs-tls-2025
  rules:
  - host: pc-api.profitokr.net
    http:
      paths:
      - backend:
          service:
            name: kube-bg-svc
            port:
              number: 80
        path: /*
        pathType: ImplementationSpecific
  - host: pc-pubsub.profitokr.net
    http:
      paths:
      - backend:
          service:
            name: kube-pubsub-producer-svc
            port:
              number: 80
        path: /*
        pathType: ImplementationSpecific
  - host: pc-enq.profitokr.net
    http:
      paths:
      - backend:
          service:
            name: kube-evq-enq-svc
            port:
              number: 80
        path: /*
        pathType: ImplementationSpecific
  - host: pc-ams.profitokr.net
    http:
      paths:
      - backend:
          service:
            name: kube-ams-svc
            port:
              number: 80
        path: /*
        pathType: ImplementationSpecific
  - host: pc-esvc.profitokr.net
    http:
      paths:
      - backend:
          service:
            name: kube-esvc-svc
            port:
              number: 80
        path: /*
        pathType: ImplementationSpecific

