apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: blue-green-ingress
  namespace: kube
  annotations:
    kubernetes.io/ingress.class: gce
    kubernetes.io/ingress.global-static-ip-name: bg-ingress-static-ip
spec:
  rules:
  - host: blue-app.local
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: kube-app-svc
            port:
              number: 80
  - host: green-app.local
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: kube-bg-svc
            port:
              number: 80

